### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by viktorstrate** [huntrar/scrape#4]
When trying to scrape overleaf with the following command, the program crashes.

I managed to fix the error by changing this line in utils.py.
I don't know if that is a sufficient solution though

```diff
 def hash_text(text):
     """Return MD5 hash of a string."""
     md5 = hashlib.md5()
-    md5.update(text)
+    md5.update(text.encode("utf-8"))
     return md5.hexdigest()
```

Scrape version: 0.10.0

```
$ scrape -all --html https://www.overleaf.com/learn/
Choosing to save images will greatly slow the crawling process.
Save images anyways? (y/n):
Storing html files in overleaf/
Traceback (most recent call last):
  File "/usr/local/bin/scrape", line 8, in <module>
    sys.exit(command_line_runner())
  File "/usr/local/lib/python3.7/site-packages/scrape/scrape.py", line 361, in command_line_runner
    scrape(args)
  File "/usr/local/lib/python3.7/site-packages/scrape/scrape.py", line 280, in scrape
    return write_single_file(args, base_dir, crawler)
  File "/usr/local/lib/python3.7/site-packages/scrape/scrape.py", line 145, in write_single_file
    infilenames += crawler.crawl_links(query)
  File "/usr/local/lib/python3.7/site-packages/scrape/crawler.py", line 91, in crawl_links
    if self.page_crawled(resp):
  File "/usr/local/lib/python3.7/site-packages/scrape/crawler.py", line 50, in page_crawled
    page_hash = utils.hash_text("".join(page_text))
  File "/usr/local/lib/python3.7/site-packages/scrape/utils.py", line 136, in hash_text
    md5.update(text)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by taybin** [comment]
Want to turn this into a PR?  It seems like a legit fix to me.

**Comment by huntrar** [comment]
This has been patched, thanks for the bug report. Pull requests are also welcome to be made.
